### ISSUE TITLE
Force squash-merging?

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/Template#64] opened 2022-08-16 20:06 UTC
@rcalvo12 @ew487 what would you think about forcing squash-merging as the only way to merge a pull, by unchecking the other options below? 

My thinking is that since it's what we [require](https://github.com/gslab-econ/ra-manual/wiki/Workflow/23843200a29e5d6a699d770d43b310d7bfb35acc#merge), we might as well enforce it. But let me know if you see any downsides that I'm missing.

If you want to do some testing let me know and I can give you access to [this repository](https://github.com/jmshapir/TestWorkflow) which we use for testing workflows.

Thanksl!

![image](https://user-images.githubusercontent.com/7840353/184974517-718eb307-6fa3-42bd-b0ba-711e14f93a63.png)

**Comment by rcalvo12** [comment] 2022-08-17 14:15
@jmshapir, per call with @ew487, we don't see any significant downsides to limiting the merge options to just "squash and merge." In the rare circumstance that a user/lab member thinks that a different type of merge would be more ideal, it is simple enough to just temporarily restore the ability to use that type of merge while closing that issue and turn it back off once the issue is pulled.

**Comment by jmshapir** [comment] 2022-08-17 14:20
@rcalvo12 @ew487 settings updated:

![image](https://user-images.githubusercontent.com/7840353/185158369-e0e9bcbe-dc52-41e6-9343-8ff9b4dea0f4.png)

I will try to execute a pull so we can test it out.

**Comment by jmshapir** [comment] 2022-08-17 14:38
Summary: In this issue we decided to enforce squash-merging on pulls. We implemented it and tested it with a pull that entails minor formatting changes to the docs. Changes brought to `main` in [441c75a](https://github.com/JMSLab/Template/commit/441c75a1bbaeba035ef91d8eb145b2b95218ee36).

**Closed** 2022-08-17 14:37 UTC
